server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp


dubbo:
  scan:
    basePackages: com.jt  #指定包路径
  application:
    name: consumer-web  #业务标识
  registry:
    address: zookeeper://192.168.83.174:2181?backup=192.168.83.174:2182,192.168.83.174:2183

  